import { createRequire } from 'node:module';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ConfigError } from '@mariachi/core';
import { toDrizzleImports } from '@mariachi/database-postgres';

/**
 * Migration files in drizzle-kit's on-disk format, so `drizzle-orm`'s migrator
 * (and `runMigrations`) can apply them and drizzle-kit tooling can read them:
 *
 *   <dir>/0000_<name>.sql            statements separated by `--> statement-breakpoint`
 *   <dir>/meta/_journal.json         ordered entries
 *   <dir>/meta/0000_snapshot.json    schema snapshot after that migration
 */

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: 'postgresql';
  entries: JournalEntry[];
}

type Snapshot = { id: string; prevId: string } & Record<string, unknown>;

type DrizzleKitApi = {
  generateDrizzleJson: (imports: Record<string, unknown>, prevId?: string) => Snapshot;
  generateMigration: (prev: Snapshot, cur: Snapshot) => Promise<string[]>;
};

const SNAPSHOT_VERSION = '7';
const BREAKPOINT = '\n--> statement-breakpoint\n';
/** Statements that can lose data. Index drops are not included: they are recreatable. */
const DESTRUCTIVE = /^\s*(DROP\s+(TABLE|TYPE|SCHEMA)|ALTER\s+TABLE\s+\S+\s+DROP\s+COLUMN|ALTER\s+TABLE\s+\S+\s+ALTER\s+COLUMN\s+\S+\s+SET\s+DATA\s+TYPE)/i;

function kit(): DrizzleKitApi {
  return createRequire(import.meta.url)('drizzle-kit/api') as DrizzleKitApi;
}

async function readJson<T>(path: string): Promise<T | null> {
  if (!existsSync(path)) return null;
  return JSON.parse(await readFile(path, 'utf8')) as T;
}

export async function readJournal(dir: string): Promise<Journal> {
  return (
    (await readJson<Journal>(join(dir, 'meta', '_journal.json'))) ?? { version: SNAPSHOT_VERSION, dialect: 'postgresql', entries: [] }
  );
}

async function latestSnapshot(dir: string, journal: Journal): Promise<Snapshot> {
  const last = journal.entries[journal.entries.length - 1];
  if (!last) return kit().generateDrizzleJson({});
  const prefix = last.tag.split('_')[0];
  const snapshot = await readJson<Snapshot>(join(dir, 'meta', `${prefix}_snapshot.json`));
  if (!snapshot) throw new ConfigError('cli/corrupt-migrations', `Missing snapshot for migration ${last.tag}`);
  return snapshot;
}

export interface PlannedMigration {
  statements: string[];
  destructive: string[];
  previous: Snapshot;
  current: Snapshot;
  journal: Journal;
}

/** Diffs the schema module against the last snapshot in `dir`. */
export async function planMigration(dir: string, schemaModule: Record<string, unknown>): Promise<PlannedMigration> {
  const journal = await readJournal(dir);
  const previous = await latestSnapshot(dir, journal);
  const current = kit().generateDrizzleJson(toDrizzleImports(schemaModule), previous.id);
  const statements = await kit().generateMigration(previous, current);
  return { statements, destructive: statements.filter((s) => DESTRUCTIVE.test(s)), previous, current, journal };
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'migration';
}

/** Writes the planned migration and returns its file path, or null when there are no changes. */
export async function writeMigration(dir: string, plan: PlannedMigration, name: string, now = Date.now()): Promise<string | null> {
  if (plan.statements.length === 0) return null;
  const idx = plan.journal.entries.length;
  const prefix = String(idx).padStart(4, '0');
  const tag = `${prefix}_${slug(name)}`;
  await mkdir(join(dir, 'meta'), { recursive: true });
  await writeFile(join(dir, `${tag}.sql`), `${plan.statements.join(BREAKPOINT)}\n`);
  await writeFile(join(dir, 'meta', `${prefix}_snapshot.json`), `${JSON.stringify(plan.current, null, 2)}\n`);
  const journal: Journal = {
    ...plan.journal,
    entries: [...plan.journal.entries, { idx, version: SNAPSHOT_VERSION, when: now, tag, breakpoints: true }],
  };
  await writeFile(join(dir, 'meta', '_journal.json'), `${JSON.stringify(journal, null, 2)}\n`);
  return join(dir, `${tag}.sql`);
}

/** drizzle.config.ts pointing drizzle-kit (studio, introspect) at the same folder. */
export function drizzleConfigSource(options: { out: string; schemaShim: string }): string {
  return `import { defineConfig } from 'drizzle-kit';

// Generated by \`mariachi db generate\`. Mariachi writes migrations itself from the
// defineTable DSL; this config lets drizzle-kit tooling (studio, check) read them.
export default defineConfig({
  dialect: 'postgresql',
  schema: '${options.schemaShim}',
  out: '${options.out}',
  dbCredentials: { url: process.env.DATABASE_URL! },
});
`;
}

/** Module drizzle-kit can load: re-exports the DSL schema compiled to pgTables. */
export function schemaShimSource(schemaImport: string, names: string[]): string {
  const lines = names.map((n) => `export const ${n} = compiled.${n};`);
  return `// Generated by \`mariachi db generate\` — do not edit.
import * as schema from '${schemaImport}';
import { toDrizzleImports } from '@mariachi/database-postgres';

const compiled = toDrizzleImports(schema) as Record<string, any>;
${lines.join('\n')}
`;
}
