#!/usr/bin/env node
// Generates packages/core/docs/packages.md from each package.json's `description` and `mariachi` fields.
// `--check` fails if the file is stale or metadata is invalid (CI).
import fs from 'node:fs';
import path from 'node:path';

const OUT = 'packages/core/docs/packages.md';
const CATEGORIES = {
  foundation: 'Foundation',
  http: 'HTTP and communication',
  data: 'Data and storage',
  async: 'Events, jobs and realtime',
  security: 'Security and access',
  domain: 'Domain features',
  tooling: 'Tooling',
};
const STATUSES = {
  beta: 'Hardened and covered by unit and integration tests. The API can still change before 1.0.',
  alpha: 'Works, but hardening is in progress. Expect breaking changes.',
};

const errors = [];

function sources(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return sources(p);
    return /\.ts$/.test(e.name) && !/\.test\.ts$/.test(e.name) ? [fs.readFileSync(p, 'utf8')] : [];
  });
}

function isExported(src, name) {
  const decl = new RegExp(`export\\s+(?:declare\\s+)?(?:async\\s+)?(?:abstract\\s+)?(?:function|class|const|let)\\s+${name}\\b`);
  const list = new RegExp(`export\\s*(?:type\\s*)?\\{[^}]*\\b${name}\\b[^}]*\\}`);
  return src.some((s) => decl.test(s) || list.test(s));
}

const packages = fs
  .readdirSync('packages')
  .filter((d) => fs.existsSync(`packages/${d}/package.json`))
  .map((dir) => {
    const pkg = JSON.parse(fs.readFileSync(`packages/${dir}/package.json`, 'utf8'));
    const m = pkg.mariachi;
    if (!pkg.description) errors.push(`${pkg.name}: missing "description"`);
    if (!m) {
      errors.push(`${pkg.name}: missing "mariachi" metadata`);
      return null;
    }
    if (!CATEGORIES[m.category]) errors.push(`${pkg.name}: unknown category "${m.category}"`);
    if (!STATUSES[m.status]) errors.push(`${pkg.name}: unknown status "${m.status}"`);
    if (!m.useWhen) errors.push(`${pkg.name}: missing mariachi.useWhen`);
    const src = fs.existsSync(`packages/${dir}/src`) ? sources(`packages/${dir}/src`) : [];
    for (const name of m.entry ?? []) {
      if (!isExported(src, name)) errors.push(`${pkg.name}: entry "${name}" is not exported from src/`);
    }
    return { dir, name: pkg.name, description: pkg.description, ...m };
  })
  .filter(Boolean);

const cell = (s) => String(s).replace(/\|/g, '\\|');
const lines = [
  '# Package catalog',
  '',
  '<!-- Generated by `pnpm docs:catalog` from each package.json (`description` and `mariachi` fields). Do not edit. -->',
  '',
  `${packages.length} packages. Status:`,
  '',
  ...Object.entries(STATUSES).map(([k, v]) => `- **${k}**: ${v}`),
  '',
];
for (const [key, title] of Object.entries(CATEGORIES)) {
  const group = packages.filter((p) => p.category === key).sort((a, b) => a.name.localeCompare(b.name));
  if (group.length === 0) continue;
  lines.push(`## ${title}`, '', '| Package | Status | What it is | Use it when | Entry points |', '| --- | --- | --- | --- | --- |');
  for (const p of group) {
    const entry = (p.entry ?? []).map((e) => `\`${e}\``).join(', ') || '-';
    // Link the package to its README (relative to packages/core/docs/) when it has one.
    const name = fs.existsSync(`packages/${p.dir}/README.md`) ? `[\`${p.name}\`](../../${p.dir}/README.md)` : `\`${p.name}\``;
    lines.push(`| ${name} | ${p.status} | ${cell(p.description)} | ${cell(p.useWhen)} | ${entry} |`);
  }
  lines.push('');
}
const content = lines.join('\n');

if (errors.length > 0) {
  for (const e of errors) console.error(`catalog: ${e}`);
  process.exit(1);
}
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== content) {
    console.error(`${OUT} is stale; run pnpm docs:catalog`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date (${packages.length} packages).`);
} else {
  fs.writeFileSync(OUT, content);
  console.log(`Wrote ${OUT} (${packages.length} packages).`);
}
